spring:
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500
server:
  port: 7878

logging:
  level:
    com.netflix.discovery: 'OFF'
    org.springframework.cloud: 'DEBUG'
    
name: zhangsan
