spring:
  application:
    name: springCloudUser
  cloud:
    consul:
      host: 127.0.0.1
      port: 8500

server:
  port: 9999

#hystirx  1.熔断对调用链路上得保护,一版作用于服务端,监听自己服务有异常则fallback
#hystirx  2.降级是对系统得保护,一版作用客户端,配合feign组件使用,监听调用其他服务接口超时或者不可用触发降级

#开启feign对hystrix支持
feign:
  hystrix:
    enabled: true
